const FETCH_EXTENSIONS_REQUESTED = 'FETCH_EXTENSIONS_REQUESTED';
const FETCH_EXTENSIONS_SUCCEEDED = 'FETCH_EXTENSIONS_SUCCEEDED';
const FETCH_EXTENSIONS_ERROR = 'FETCH_EXTENSIONS_SUCCEEDED';
const SET_IS_LOADING = 'SET_IS_LOADING';

export default {
    FETCH_EXTENSIONS_REQUESTED,
    FETCH_EXTENSIONS_SUCCEEDED,
    FETCH_EXTENSIONS_ERROR,
    SET_IS_LOADING
};
